#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
JENKINS_VERSION='2.89.3'

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Create user for jenkins
echo "* create user for jenkins"
groupadd -g 10001 jenkins
useradd -u 10001 -g jenkins -d /home/jenkins -s /usr/bin/bash jenkins
mkdir /home/jenkins; chown jenkins:jenkins /home/jenkins

# Download and enable jenkins
echo "* download and enable jenkins"
wget -c -O /opt/jenkins.war http://mirrors.jenkins-ci.org/war-stable/${JENKINS_VERSION}/jenkins.war
svccfg import /root/jenkins.xml

# Create ssl folder for nginx
echo "* create ssl folder for nginx"
mkdir -p /opt/local/etc/nginx/ssl

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
